1.B:
  concept: B
  group: '1'
1.C:
  concept: C
  group: '1'
1.D:
  concept: D
  group: '1'
1.F:
  concept: F
  group: '1'
2.B:
  concept: B
  group: '2'
2.C:
  concept: C
  group: '2'
2.F:
  concept: F
  group: '2'
comb.1.A\n2.A:
  concept: 1.A\n2.A
  group: comb
comb.1.E\n2.E:
  concept: 1.E\n2.E
  group: comb
comb.1.G\n2.G:
  concept: 1.G\n2.G
  group: comb
comb.1.H\n2.H:
  concept: 1.H\n2.H
  group: comb
comb.1.I\n2.I:
  concept: 1.I\n2.I
  group: comb
1.B_2.B:
  label: input
  s: 1.B
  t: 2.B
1.C_2.C:
  label: input
  s: 1.C
  t: 2.C
1.D_2.C:
  label: input
  s: 1.D
  t: 2.C
1.E\n2.E_1.B:
  label: input
  s: 1.E\n2.E
  t: 1.B
1.F_1.A\n2.A:
  label: input
  s: 1.F
  t: 1.A\n2.A
1.F_2.B:
  label: overlaps
  s: 1.F
  t: 2.B
1.F_2.F:
  label: overlaps
  s: 1.F
  t: 2.F
1.G\n2.G_1.F:
  label: input
  s: 1.G\n2.G
  t: 1.F
1.G\n2.G_2.F:
  label: input
  s: 1.G\n2.G
  t: 2.F
1.H\n2.H_1.F:
  label: input
  s: 1.H\n2.H
  t: 1.F
1.H\n2.H_2.B:
  label: input
  s: 1.H\n2.H
  t: 2.B
1.I\n2.I_2.F:
  label: input
  s: 1.I\n2.I
  t: 2.F
2.B_1.A\n2.A:
  label: input
  s: 2.B
  t: 1.A\n2.A
2.C_1.B:
  label: inferred
  s: 2.C
  t: 1.B
2.F_1.A\n2.A:
  label: input
  s: 2.F
  t: 1.A\n2.A
